server:
  port: 8001

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true


